// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  hello: "Hello World from the cloudflare context!";
  DB: D1Database;
  ASSETS: Fetcher;
}
