#:schema node_modules/wrangler/config-schema.json
name = "nextjs-worker"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[vars]
hello = 'Hello World from the cloudflare context!'

[[d1_databases]]
binding = "DB"
database_name = "hexa"
database_id = "da7f8a20-83d9-4dd1-9a33-4ffdf4956933"
migrations_dir = "./drizzle/migrations"
