#:schema node_modules/wrangler/config-schema.json
name = "hexa-com"
main = ".worker-next/index.mjs"
workers_dev = false
routes = [
  { pattern = "app.hexa.im", custom_domain = true }
]

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1

[vars]
hello = 'Hello World from Hexa!'

[[d1_databases]]
binding = "DB"
database_name = "hexa"
database_id = "da7f8a20-83d9-4dd1-9a33-4ffdf4956933"
preview_database_id = "f1a166ed-95cd-42dd-887e-bb0e34395ebb"
migrations_dir = "./drizzle/migrations"

[env.staging]
name="hexa-xyz"
routes = [
  { pattern = "app.xyz.hexa.im", custom_domain = true }
]
[env.staging.vars]
hello = 'Hello World from Hexa-XYZ!'