default_stages: [commit, manual]
repos:
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: npx biome check --files-ignore-unknown=true --no-errors-on-unmatched --fix --unsafe
        language: system
        types: [text]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
