packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@biomejs/biome": "1.9.4"
  "@cloudflare/workers-types": "4.20241112.0"
  "@commitlint/cli": "19.3.0"
  "@commitlint/config-conventional": "19.2.2"
  "@dnd-kit/core": "6.2.0"
  "@dnd-kit/sortable": "9.0.0"
  "@dnd-kit/utilities": "3.2.2"
  "@dotenvx/dotenvx": "1.26.0"
  "@ebay/nice-modal-react": "1.2.13"
  "@heroicons/react": "2.1.5"
  "@hono/zod-validator": "0.4.2"
  "@hookform/resolvers": "3.6.0"
  "@iconify/react": "5.1.0"
  "@internationalized/date": "3.6.0"
  "@lucia-auth/adapter-sqlite": "3.0.2"
  "@marsidev/react-turnstile": "1.1.0"
  "@nextui-org/react": "2.6.8"
  "@nextui-org/system": "2.4.3"
  "@nextui-org/theme": "2.4.1"
  "@opennextjs/cloudflare": "https://pkg.pr.new/@opennextjs/cloudflare@192"
  "@radix-ui/react-icons": "1.3.0"
  "@radix-ui/react-scroll-area": "1.1.0"
  "@radix-ui/react-slot": "1.1.0"
  "@react-aria/i18n": "3.12.2"
  "@react-email/components": "0.0.19"
  "@react-types/shared": "3.26.0"
  "@storybook/addon-essentials": "8.4.3"
  "@storybook/addon-interactions": "8.4.3"
  "@storybook/addon-styling": "1.3.7"
  "@storybook/addon-themes": "8.4.3"
  "@storybook/nextjs": "8.4.3"
  "@storybook/react": "8.4.3"
  "@storybook/test": "8.4.3"
  "@tailwindcss/forms": "0.5.7"
  "@tailwindcss/typography": "0.5.13"
  "@tanstack/react-query-devtools": "5.50.1"
  "@tanstack/react-query-next-experimental": "5.50.1"
  "@tanstack/react-query": "5.50.1"
  "@tanstack/react-table": "8.20.5"
  "@types/lodash": "4.17.5"
  "@types/node": "22.10.2"
  "@types/react-dom": "19.0.2"
  "@types/react": "19.0.2"
  "@vercel/analytics": "1.3.1"
  "@vercel/speed-insights": "1.0.12"
  "arctic": "1.9.1"
  "autoprefixer": "10.4.19"
  "aws4fetch": "1.0.18"
  "better-sqlite3": "11.5.0"
  "caniuse-lite": "1.0.30001689"
  "class-variance-authority": "0.7.0"
  "clsx": "2.1.1"
  "concurrently": "9.1.0"
  "cookie": "1.0.2"
  "dotenv-run-script": "0.4.1"
  "dotenv": "16.4.5"
  "drizzle-kit": "0.28.1"
  "drizzle-orm": "0.36.4"
  "drizzle-zod": "0.5.1"
  "framer-motion": "11.11.15"
  "geist": "1.3.1"
  "hono": "4.6.14"
  "intl-parse-accept-language": "1.0.0"
  "lodash": "4.17.21"
  "lucia": "3.2.2"
  "lucide-react": "0.460.0"
  "mintlify": "4.0.286"
  "next-themes": "0.3.0"
  "next": "15.1.2"
  "oslo": "1.2.0"
  "postcss-import": "16.1.0"
  "postcss": "8.4.38"
  "qrcode.react": "4.1.0"
  "random-word-slugs": "0.1.7"
  "react-dom": "19.0.0"
  "react-email": "2.1.4"
  "react-hook-form": "7.53.2"
  "react": "19.0.0"
  "recharts": "2.13.3"
  "resend": "3.3.0"
  "sonner": "1.5.0"
  "storybook": "8.4.3"
  "syncpack": "13.0.0"
  "tailwind-merge": "2.3.0"
  "tailwind-scrollbar-hide": "1.1.7"
  "tailwindcss-animate": "1.0.7"
  "tailwindcss-radix": "2.9.0"
  "tailwindcss": "3.4.4"
  "tsx": "4.7.1"
  "turbo": "2.3.3"
  "type-fest": "4.27.0"
  "typescript": "5.7.2"
  "ua-parser-js": "2.0.0"
  "ultracite": "4.1.14"
  "usehooks-ts": "3.1.0"
  "wrangler": "3.99.0"
  "zod": "3.23.8"
  
 