packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@biomejs/biome": "1.9.4"
  "@cloudflare/workers-types": "4.20241112.0"
  "@codesandbox/sandpack-react": "^2.6.4"
  "@commitlint/cli": "19.3.0"
  "@commitlint/config-conventional": "19.2.2"
  "@dnd-kit/core": "6.2.0"
  "@dnd-kit/sortable": "9.0.0"
  "@dnd-kit/utilities": "3.2.2"
  "@dotenvx/dotenvx": "1.26.0"
  "@ebay/nice-modal-react": "1.2.13"
  "@emotion/is-prop-valid": "^1.3.1"
  "@heroicons/react": "2.1.5"
  "@hono/zod-validator": "0.4.2"
  "@hookform/resolvers": "3.6.0"
  "@iconify/icons-solar": "1.2.3"
  "@iconify/react": "5.0.2"
  "@internationalized/date": "3.6.0"
  "@libsql/client": "0.14.0"
  "@lucia-auth/adapter-sqlite": "3.0.2"
  "@mapbox/rehype-prism": "^0.6.0"
  "@marsidev/react-turnstile": "1.1.0"
  "@nextui-org/react": "2.6.8"
  "@nextui-org/system": "2.4.3"
  "@nextui-org/theme": "2.4.1"
  "@opennextjs/cloudflare": "https://pkg.pr.new/@opennextjs/cloudflare@192"
  "@radix-ui/react-icons": "1.3.0"
  "@radix-ui/react-scroll-area": "^1.0.5"
  "@radix-ui/react-slot": "1.1.0"
  "@react-aria/focus": "3.19.0"
  "@react-aria/i18n": "3.12.4"
  "@react-aria/interactions": "3.22.5"
  "@react-aria/selection": "3.21.0"
  "@react-aria/ssr": "3.9.7"
  "@react-aria/utils": "3.26.0"
  "@react-aria/virtualizer": "4.1.0"
  "@react-aria/visually-hidden": "3.8.18"
  "@react-email/components": "0.0.19"
  "@react-stately/data": "3.12.0"
  "@react-stately/layout": "4.1.0"
  "@react-stately/tree": "3.8.6"
  "@react-types/shared": "3.26.0"
  "@rehooks/local-storage": "^2.4.5"
  "@storybook/addon-essentials": "8.4.3"
  "@storybook/addon-interactions": "8.4.3"
  "@storybook/addon-styling": "1.3.7"
  "@storybook/addon-themes": "8.4.3"
  "@storybook/nextjs": "8.4.3"
  "@storybook/react": "8.4.3"
  "@storybook/test": "8.4.3"
  "@tailwindcss/forms": "0.5.7"
  "@tailwindcss/typography": "0.5.13"
  "@tanstack/react-query-devtools": "5.50.1"
  "@tanstack/react-query-next-experimental": "5.50.1"
  "@types/parse-numeric-range": "^0.0.1"
  "@tanstack/react-query": "5.50.1"
  "@tanstack/react-table": "8.20.5"
  "@tanstack/react-virtual": "3.10.9"
  "@types/lodash": "4.17.5"
  "@types/mdx": "^2.0.5"
  "@types/node": "22.10.2"
  "@types/react-dom": "19.0.2"
  "@types/react": "19.0.2"
  "@vercel/analytics": "1.3.1"
  "@vercel/speed-insights": "1.0.12"
  "arctic": "2.3.3"
  "autoprefixer": "10.4.19"
  "aws4fetch": "1.0.18"
  "better-sqlite3": "11.5.0"
  "caniuse-lite": "1.0.30001689"
  "canvas-confetti": "^1.9.2"
  "class-variance-authority": "0.7.0"
  "clsx": "2.1.1"
  "cmdk": "^0.2.0"
  "color2k": "2.0.3"
  "concurrently": "9.1.0"
  "contentlayer2": "0.5.3"
  "cookie": "1.0.2"
  "date-fns": "4.1.0"
  "dotenv-run-script": "0.4.1"
  "dotenv": "16.4.5"
  "drizzle-kit": "0.28.1"
  "drizzle-orm": "0.36.4"
  "drizzle-zod": "0.5.1"
  "esbuild-plugin-raw": "0.1.8"
  "framer-motion": "11.11.15"
  "geist": "1.3.1"
  "github-slugger": "^2.0.0"
  "gray-matter": "^4.0.3"
  "hast-util-to-html": "9.0.3"
  "hono": "4.6.14"
  "intl-parse-accept-language": "1.0.0"
  "lodash": "4.17.21"
  "lucia": "3.2.2"
  "lucide-react": "0.460.0"
  "marked": "^5.1.0"
  "match-sorter": "8.0.0"
  "mini-svg-data-uri": "1.4.4"
  "mintlify": "4.0.286"
  "mitt": "3.0.1"
  "next-contentlayer2": "0.5.3"
  "next-themes": "0.4.3"
  "next": "15.1.2"
  "node-fetch": "3.3.2"
  "oslo": "1.2.0"
  "parse-numeric-range": "1.2.0"
  "postcss-import": "16.1.0"
  "postcss": "8.4.38"
  "posthog-js": "1.197.0"
  "prism-react-renderer": "^1.2.1"
  "qrcode.react": "4.1.0"
  "querystring": "^0.2.1"
  "random-word-slugs": "0.1.7"
  "react-dom": "19.0.0"
  "react-email": "2.1.4"
  "react-hook-form": "7.51.3"
  "react-icons": "^4.10.1"
  "react-live": "^4.1.8"
  "react-multi-ref": "^1.0.1"
  "react-wrap-balancer": "1.0.0"
  "react": "19.0.0"
  "recharts": "2.13.3"
  "refractor": "3.3.1"
  "rehype-parse": "9.0.1"
  "rehype-pretty-code": "^0.14.0"
  "rehype-slug": "6.0.0"
  "rehype": "13.0.2"
  "remark-gfm": "4.0.0"
  "remark": "^15.0.1"
  "resend": "3.3.0"
  "rss": "1.2.2"
  "scroll-into-view-if-needed": "3.1.0"
  "sharp": "^0.32.1"
  "shelljs": "^0.8.4"
  "sonner": "1.5.0"
  "storybook": "8.4.3"
  "swr": "2.2.5"
  "syncpack": "13.0.0"
  "tailwind-merge": "2.3.0"
  "tailwind-scrollbar-hide": "1.1.7"
  "tailwind-variants": "^0.1.20"
  "tailwindcss-animate": "1.0.7"
  "tailwindcss-radix": "2.9.0"
  "tailwindcss": "3.4.4"
  "tsx": "4.7.1"
  "turbo": "2.3.3"
  "type-fest": "4.27.0"
  "typescript": "5.7.2"
  "ua-parser-js": "2.0.0"
  "ultracite": "4.1.14"
  "unified": "^11.0.5"
  "unist-util-visit": "5.0.0"
  "usehooks-ts": "3.1.0"
  "wrangler": "3.99.0"
  "yaml": "2.6.1"
  "zod": "3.23.8"
  "zustand": "5.0.1"
  "@types/marked": "^5.0.0"
  "@types/refractor": "^3.0.2"
