#:schema node_modules/wrangler/config-schema.json
name = "hexa-www"
main = ".open-next/worker.js"
workers_dev = false
routes = [
  { pattern = "www.hexa.im", custom_domain = true },
]

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability]
enabled = true
head_sampling_rate = 1


# =================== Staging ===================
[env.staging]
name="hexa-www-xyz"
routes = [
  { pattern = "www.ml.kg", custom_domain = true },
]
