// Generated by Wrangler by running `wrangler types`

interface Env {
	REDIRECT: KVNamespace;
	HOME_URL: string;
	REDIRECT_DATASET: string;
	CF_WAE_API_TOKEN: string;
	CF_WAE_ACCOUNT_ID: string;
	REDIRECT_ANALYTICS: AnalyticsEngineDataset;
	ASSETS: Fetcher;
}
