#:schema node_modules/wrangler/config-schema.json
name = "hexa-redirect"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[env.local]
routes = [
  { pattern = "localhost:7001", custom_domain = true }
]

[env.production]
routes = [
  { pattern = "hexa.im", custom_domain = true }
]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "REDIRECT"
id = "1eed1bf2d8ae4aa9a112121be24ad5d7"

# =================== Staging ===================

[env.staging]
name="hexa-redirect-xyz"
workers_dev = true
routes = [
  { pattern = "redirect.xyz.hexa.im", custom_domain = true }
]

[[env.staging.kv_namespaces]]
binding = "REDIRECT"
id = "082a86f93ac54912af21bdf8ae170ade"