// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	APP_KV: KVNamespace;
	RESEND_API_KEY: string;
	OAUTH_GITHUB_CLIENT_ID: string;
	OAUTH_GITHUB_CLIENT_SECRET: string;
	OAUTH_GOOGLE_CLIENT_ID: string;
	OAUTH_GOOGLE_CLIENT_SECRET: string;
	CF_TURNSTILE_SECRET_KEY: string;
	STORAGE_ACCESS_KEY_ID: string;
	STORAGE_SECRET_ACCESS_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	DEFAULT_DOMAINS: string;
	REDIRECT_DATASET: string;
	CF_WAE_API_TOKEN: string;
	CF_WAE_ACCOUNT_ID: string;
	CF_ZONE_ID: string;
	CF_EDIT_CUSTOM_HOSTNAME_API_TOKEN: string;
	DB: D1Database;
	REDIRECT_ANALYTICS: AnalyticsEngineDataset;
	ASSETS: Fetcher;
}
