// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	REDIRECT: KVNamespace;
	hello: "Hello World from Hexa!";
	RESEND_API_KEY: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	CLOUDFLARE_TURNSTILE_SECRET_KEY: string;
	STORAGE_ACCESS_KEY_ID: string;
	STORAGE_SECRET_ACCESS_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
