name: Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to"
        type: choice
        options:
          - staging
          - production
        required: true
        default: "production"
  push:
    branches:
      - main
      - xyz

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yaml
    with:
      app_name: app
      wrangler_toml_var: APP_WRANGLER_TOML
    secrets: inherit
